{
 "title": "Klever Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_epoch_number", "legendFormat": "Current Epoch" }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_current_slot", "legendFormat": "Current Slot" },
    { "expr": "klv_slots_per_epoch", "legendFormat": "Slots Per Epoch" },
    { "expr": "klv_slot_duration / 1000", "legendFormat": "Seconds Per Block" }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_live_validator_nodes", "legendFormat": "Live Validators" },
    { "expr": "klv_num_validators", "legendFormat": "Epoch Validators" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "klv_num_connected_peers", "legendFormat": "#Connected Peers" },
    { "expr": "klv_connected_nodes", "legendFormat": "#Connected Nodes" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_connected_nodes", "legendFormat": "Connected Nodes" },
    { "expr": "klv_num_connected_peers", "legendFormat": "Connected Peers" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Total Validator Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Proposed Blocks" },
    { "expr": "klv_count_accepted_blocks", "legendFormat": "Accepted Blocks" }
   ]
  },
  {
   "title": "Node State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Klever\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"klever-node-status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"klv_node_type\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus", "legendFormat": "Validator Signed" },
    {
     "expr": "klv_count_consensus_accepted_blocks",
     "legendFormat": "Validator Accepted"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent", "legendFormat": "Memory Usage %" },
    { "expr": "klv_cpu_load_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"Klever\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"klever-node-status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"klv_node_type\" or r[\"_field\"] == \"klv_app_version\" or r[\"_field\"] == \"klv_consensus_slot_state\" or r[\"_field\"] == \"klv_consensus_state\" or r[\"_field\"] == \"klv_node_display_name\")\r\n  |> last(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Synced Slots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_highest_final_nonce", "legendFormat": "Block Height" },
    { "expr": "klv_probable_highest_nonce", "legendFormat": "Node Height" }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  },
  {
   "title": "Current Load",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_tx_pool_load", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Peak Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peak_tps", "legendFormat": "TX Peak" }
   ]
  }
 ]
}